# Generated by Django 5.0.2 on 2024-08-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='name',
        ),
    ]
