# Generated by Django 5.0.2 on 2024-08-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coustomer',
            new_name='customer',
        ),
    ]
